---
sidebar: sidebar
permalink: backup/anf-cba-overview.html
keywords: tr4959, 4959, overview, introduction
summary: "This technical report provides best practices for SAP HANA data protection on Azure NetApp Files (ANF) with NetApp BlueXP Cloud Backup for Applications (CBA). The document covers CBA concepts, configuration best practices, and descriptions of operation workflows for backup, and restore and recovery operations."
---

= TR-4959: SAP HANA on ANF - Backup and recovery with cloud backup for applications
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2023-03-16 10:24:27.190139
//

Nils Bauer, NetApp

[.lead]
This technical report provides best practices for SAP HANA data protection on Azure NetApp Files (ANF) with NetApp BlueXP Cloud Backup for Applications (CBA). The document covers CBA concepts, configuration best practices, and descriptions of operation workflows for backup, and restore and recovery operations.

Companies today require continuous, uninterrupted availability for their SAP applications. They expect consistent performance levels in the face of ever-increasing volumes of data and routine maintenance tasks, such as system backups. Performing backups of SAP databases is a critical task and can have a significant performance effect on the production SAP system.

Backup windows are shrinking while the amount of data to be backed up is increasing. Therefore, it is difficult to find a time when you can perform backups with a minimal effect on business processes. The time needed to restore and recover SAP systems is a concern because downtime for SAP production and nonproduction systems must be minimized to reduce cost to the business.
 
link:anf-cba-backup-and-recovery-using-azure-netapp-files.html[Next: Backup and recovery using Azure NetApp Files.]
