---
sidebar: sidebar
permalink: backup/saphana-br-scs-where-to-find-additional-information.html
keywords:
summary:
---

= Where to find additional information and version history
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-02-15 15:58:31.001837
//

link:saphana-br-scs-advanced-configuration-and-tuning.html[Previous: Advanced configuration and tuning.]

To learn more about the information that is described in this document, review the following documents and/or websites:

* SnapCenter Resources Page
+
https://www.netapp.com/us/documentation/snapcenter-software.aspx[https://www.netapp.com/us/documentation/snapcenter-software.aspx^]

* SnapCenter Software Documentation
+
https://docs.netapp.com/us-en/snapcenter/index.html[https://docs.netapp.com/us-en/snapcenter/index.html^]

* TR-4667: Automating SAP System Copies Using the SnapCenter
+
https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf[https://www.netapp.com/pdf.html?item=/media/17111-tr4667pdf.pdf^]

* TR-4719: SAP HANA System Replication, Backup and Recovery with SnapCenter
+
https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf[https://www.netapp.com/pdf.html?item=/media/17030-tr4719pdf.pdf^]

* TR-4018: Integrating NetApp ONTAP Systems with SAP Landscape Management
+
https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf[https://www.netapp.com/pdf.html?item=/media/17195-tr4018pdf.pdf^]

* TR-4646: SAP HANA Disaster Recovery with Storage Replication
+
https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf[https://www.netapp.com/pdf.html?item=/media/8584-tr4646pdf.pdf^]

=== Version history

|===
|Version |Date |Document version history

|Version 1.0
|July 2017
a|* Initial release.
|Version 1.1
|September 2017
a|* Added the section “Advanced Configuration and Tuning.”
* Minor corrections.
|Version 2.0
|March 2018
a|* Updates to cover SnapCenter 4.0:
New data volume resource
Improved Single File SnapRestore operation
|Version 3.0
|January 2020
a|* Added the section “SnapCenter Concepts and Best Practices.”
* Updates to cover SnapCenter 4.3:
Automatic discovery
Automated restore and recovery
Support of HANA MDC multiple tenants
Single-tenant restore operation
|Version 3.1
|July 2020
a|* Minor updates and corrections:
NFSv4 support with SnapCenter 4.3.1
Configuration of SSL communication
Central plug-in deployment for Linux on IBM Power
|Version 3.2
|November 2020
a|* Added the required database user privileges for HANA 2.0 SPS5.
|Version 3.3
|May 2021
a|* Updated the SSL hdbsql configuration section.
* Added Linux LVM support.
|Version 3.4
|August 2021
a|* Added the disable auto discovery configuration description.
|Version 3.5
|February 2022
a|* Minor updates to cover SnapCenter 4.6 and auto discovery support for HANA System Replication-enabled HANA systems.
|===
