---
sidebar: sidebar
permalink: lifecycle/lama-ansible-conclusion.html
keywords: conclusion, additional information, version history
summary: The integration of a modern automation framework like Ansible into SAP LaMa provisioning workflows gives customers a flexible solution to address standard or more complex infrastructure requirements.
---

= Conclusion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2023-01-30 15:53:02.817313
//

link:lama-ansible-appendix--provider-script-configuration-and-ansible-playbooks.html[Previous: Provider script configuration and Ansible playbooks.]

[.lead]
The integration of a modern automation framework like Ansible into SAP LaMa provisioning workflows gives customers a flexible solution to address standard or more complex infrastructure requirements.

== Where to find additional information

To learn more about the information that is described in this document, review the following documents and/or websites:

* Collections in the NetApp Namespace
+
https://docs.ansible.com/ansible/latest/collections/netapp/index.html[https://docs.ansible.com/ansible/latest/collections/netapp/index.html^] 

* Documentation about Ansible Integration and Sample Ansible Playbooks
+
https://github.com/sap-linuxlab/demo.netapp_ontap[https://github.com/sap-linuxlab/demo.netapp_ontap^]

* General Ansible and NetApp Integration
+
https://www.ansible.com/integrations/infrastructure/netapp[https://www.ansible.com/integrations/infrastructure/netapp^]

* Blog on integrating SAP LaMa with Ansible
+
https://blogs.sap.com/2020/06/08/outgoing-api-calls-from-sap-landscape-management-lama-with-automation-studio/[https://blogs.sap.com/2020/06/08/outgoing-api-calls-from-sap-landscape-management-lama-with-automation-studio/^]

* SAP Landscape Management 3.0, Enterprise Edition Documentation
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/4df88a8f418c5059e10000000a42189c.html[https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/4df88a8f418c5059e10000000a42189c.html#loio4df88a8f418c5059e10000000a42189c^]

* SAP LaMa Documentation – Provider Definitions
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/bf6b3e43340a4cbcb0c0f3089715c068.html[https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/bf6b3e43340a4cbcb0c0f3089715c068.html^]

* SAP LaMa Documentation - Custom Hooks
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/139eca2f925e48738a20dbf0b56674c5.html[https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/139eca2f925e48738a20dbf0b56674c5.html^]

* SAP LaMa Documentation - Configuring SAP Host Agent Registered Scripts
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/250dfc5eef4047a38bab466c295d3a49.html[https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/250dfc5eef4047a38bab466c295d3a49.html^]

* SAP LaMa Documentation - Parameters for Custom Operations and Custom Hooks
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/0148e495174943de8c1c3ee1b7c9cc65.html[https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/0148e495174943de8c1c3ee1b7c9cc65.html^]

* SAP LaMa Documentation - Adaptive Design
+
https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/737a99e86f8743bdb8d1f6cf4b862c79.html[https://help.sap.com/doc/700f9a7e52c7497cad37f7c46023b7ff/3.0.11.0/en-US/737a99e86f8743bdb8d1f6cf4b862c79.html^]

* NetApp Product Documentation
+
https://www.netapp.com/support-and-training/documentation/[https://www.netapp.com/support-and-training/documentation/^]

== Version history

|===
|Version |Date |Document version history

|Version 1.0
|January 2023
|Initial release
|===
