---
sidebar: sidebar
permalink: lifecycle/sc-copy-clone-where-to-find-additional-information.html
keywords:
summary:
---

= Where to find additional information
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./../media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2022-05-23 12:08:56.606046
//

link:sc-copy-clone-sap-system-clone-with-snapcenter.html[Previous: SAP system clone with SnapCenter.]

To learn more about the information described in this document, refer to the following documents and/or websites:

* TR-4614: SAP HANA Backup and Recovery with SnapCenter
+
https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html[https://docs.netapp.com/us-en/netapp-solutions-sap/backup/saphana-br-scs-overview.html^]

* https://www.netapp.com/us/media/tr-4018.pdf[TR-4018: Integrating NetApp ONTAP Systems with SAP Landscape Management^]
+
https://www.netapp.com/us/media/tr-4018.pdf[https://www.netapp.com/us/media/tr-4018.pdf^]

* https://www.netapp.com/us/media/tr-4646.pdf[TR-4646: SAP HANA Disaster Recovery with Storage Replication^]
+
https://www.netapp.com/us/media/tr-4646.pdf[https://www.netapp.com/us/media/tr-4646.pdf^]

* TR-4436: SAP HANA on NetApp All Flash FAS Systems with Fibre Channel Protocol
+
https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_fc_introduction.html[https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_fc_introduction.html^]

* TR-4435: SAP HANA on NetApp All Flash FAS Systems with NFS
+
https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_nfs_introduction.html[https://docs.netapp.com/us-en/netapp-solutions-sap/bp/saphana_aff_nfs_introduction.html^]

* NetApp SAP Software Solutions product page
+
http://www.netapp.com/us/solutions/applications/sap/index.aspx[http://www.netapp.com/us/solutions/applications/sap/index.aspx^]

== Version History

|===
|Version |Date |Document Version History

|Version 1.0
|February 2018
|Initial release.
|Version 2.0
|February 2021
|Complete rewrite covering SnapCenter 4.3 and improved automation scripts.
New workflow description for system refresh and system clone operations.
|Version 3.0
|May 2022
|Updated workflow for SnapCenter 4.6 P1.
|===
